# Generated by Django 5.0.7 on 2024-11-13 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('head', models.CharField(max_length=255, verbose_name='Руководитель')),
                ('staff_count', models.IntegerField(verbose_name='Численность')),
            ],
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная зарплата')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.positions', verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('description', models.TextField(verbose_name='Описание')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to='app.employees', verbose_name='Создатель')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_reports', to='app.departments', verbose_name='Отдел')),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='reports',
            field=models.ManyToManyField(blank=True, to='app.reports', verbose_name='Отчеты'),
        ),
        migrations.AddField(
            model_name='departments',
            name='reports',
            field=models.ManyToManyField(blank=True, to='app.reports', verbose_name='Отчеты'),
        ),
    ]
