# Generated by Django 5.0.7 on 2024-11-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(blank=True, default=1, verbose_name='Salary'),
            preserve_default=False,
        ),
    ]
