# Generated by Django 5.0.7 on 2024-11-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employees_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='salary',
            field=models.IntegerField(blank=True, verbose_name='Зарплата'),
        ),
    ]
