# Generated by Django 5.0.7 on 2024-11-14 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employees_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='app.departments', verbose_name='Отдел'),
        ),
    ]
